<a href="https://colab.research.google.com/github/SupriyaKapse/Supriya_FDS/blob/main/SupriyaKapse13AUG2021_first_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Welcome supriya kapse')

Welcome supriya kapse


In [ ]:
num1=20
num2=10
num3=num1+num2
print(num3)

30


In [ ]:
a=2
b=9
a
b


9

In [ ]:
a=5
b=4
print('a= '+str(a) +' '+'and b='+str(b))

a= 5 and b=4


In [ ]:
a=10
type(a)


int

In [ ]:
s1='Supriya kapse'
type(s1)

str

In [ ]:
f=2.3455567
type(f)

float

In [ ]:
$y=x^2$

SyntaxError: ignored

#supriya
##sup
###supriya kapse
####supriya


$y=x^2$

In [ ]:
a=[1,2,3]
a

[1, 2, 3]

In [ ]:
type(a)

list

In [ ]:
b=[4,5,6,7]
b

[4, 5, 6, 7]

In [ ]:
c=[]
for i in range(len(a)):
  c.append(a[i]+b[i])
c

[5, 7, 9]

In [ ]:
import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")

Sleeping
Done Sleeping


In [ ]:
!ls /bin

bash	       hostname       su
bunzip2        journalctl     sync
bzcat	       kill	      systemctl
bzcmp	       kmod	      systemd
bzdiff	       less	      systemd-ask-password
bzegrep        lessecho       systemd-escape
bzexe	       lessfile       systemd-hwdb
bzfgrep        lesskey	      systemd-inhibit
bzgrep	       lesspipe       systemd-machine-id-setup
bzip2	       ln	      systemd-notify
bzip2recover   login	      systemd-sysusers
bzless	       loginctl       systemd-tmpfiles
bzmore	       ls	      systemd-tty-ask-password-agent
cat	       lsblk	      tar
chgrp	       lsmod	      tempfile
chmod	       mkdir	      touch
chown	       mknod	      true
cp	       mktemp	      udevadm
dash	       more	      ulockmgr_server
date	       mount	      umount
dd	       mountpoint     uname
df	       mv	      uncompress
dir	       networkctl     vdir
dmesg	       nisdomainname  wdctl
dnsdomainname  pidof	      which
domainname     ps	      ypdomainname
echo	       pwd	      zcat
egrep	     

In [ ]:
%%html
<marquee style='width: 30%; color: blue;'><b>Whee!</b></marquee>

In [ ]:
import numpy as np


In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
np.ndarray

numpy.ndarray

In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.itemsize

8

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b=np.array([[1,2,3],[6,7,8]])
b

array([[1, 2, 3],
       [6, 7, 8]])

In [ ]:
c=b.reshape(3,2)
c

array([[1, 2],
       [3, 6],
       [7, 8]])

In [ ]:
d=np.array([['a','b','c','d','e'],['f','i','j','k','l']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'i', 'j', 'k', 'l']], dtype='<U1')