In [ ]:
import numpy
numpy.__version__

'1.19.5'

In [ ]:
list1=[]
list1

[]

In [ ]:
type(list1)

list

In [ ]:
list2=list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list3=[str(c) for c in list2]
list3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
list4=[1,1.002,'Supriya','c',True]
list4

[1, 1.002, 'Supriya', 'c', True]

In [ ]:
type(list4)

list

In [ ]:
[type(item) for item in list4]

[int, float, str, str, bool]

In [ ]:
import array as ar
L=list(range(10))
A=ar.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [ ]:
np.array([10.001,2,3,4])

array([10.001,  2.   ,  3.   ,  4.   ])

In [ ]:
np.array([10,2.009,3,4,5],dtype='float32')

array([10.   ,  2.009,  3.   ,  4.   ,  5.   ], dtype=float32)

In [ ]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,5),dtype='float')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full((2,2),24)

array([[24, 24],
       [24, 24]])

In [ ]:
np.full((3,4),2.01)

array([[2.01, 2.01, 2.01, 2.01],
       [2.01, 2.01, 2.01, 2.01],
       [2.01, 2.01, 2.01, 2.01]])

In [ ]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,4))

array([[0.34395059, 0.99210438, 0.74344512, 0.95471909],
       [0.98015249, 0.82706891, 0.19878433, 0.99809459],
       [0.4124775 , 0.68295683, 0.11175878, 0.26637434]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 1.76412915e+00, -1.49183118e+00, -8.16007236e-01],
       [-2.13612857e-01,  4.11775646e-01, -7.60245408e-01],
       [-1.14628812e+00, -1.16489898e-01,  6.98511036e-04]])

In [ ]:
np.random.normal(0,10,(3,3))

array([[14.85061849, -1.40069842,  1.2950176 ],
       [ 8.07290152, -3.10272464, -0.35088391],
       [ 0.78806116, -9.1549983 , -9.87931199]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
np.random.seed(10)
a=np.random.randint(10,size=6)
a

array([9, 4, 0, 1, 9, 0])

In [ ]:
import numpy as np
np.random.seed(100)
a=np.random.randint(200,size=(5,6,7))
a

array([[[  8,  24,  67, 103,  87,  79, 176],
        [138,  94, 180,  98,  53,  66,  14],
        [ 34,  24, 143, 107,  60,  58, 144],
        [137,  93,  86, 130, 155, 108, 132],
        [159, 129, 141, 100,   4,  91, 187],
        [ 67, 135,  49, 175, 193,  61,  14]],

       [[183, 199,  80,   2, 121, 105, 147],
        [ 63, 181,  27,  56, 113, 158, 176],
        [ 47, 167, 109,  38, 172,  18, 192],
        [184, 162, 181,  17,  72,  13, 106],
        [ 30,  17,  53,  68, 178,  91, 181],
        [ 78,   0,  13, 185, 106, 131,  70]],

       [[131, 138, 188, 131, 105, 176, 180],
        [ 43,  36,   5,  71,  38,  94, 170],
        [ 84,  95, 114, 119,  76,  33,  58],
        [102, 170, 150,   0, 183, 147,  53],
        [196, 190,  50, 196, 163, 151,   9],
        [176,  21, 153, 182,   6, 165, 102]],

       [[122, 116, 186,  39, 107,  51,  30],
        [121,  66, 152, 183,  17,  45,  89],
        [173,  35,  16,  12,  86, 109,  67],
        [ 20, 138,   8, 158, 140, 146,  93],
    

In [ ]:
import numpy as np
np.random.seed(100)
b=np.random.randint(200,size=(2,2,3))
b

array([[[  8,  24,  67],
        [103,  87,  79]],

       [[176, 138,  94],
        [180,  98,  53]]])

In [ ]:
b.shape

(2, 2, 3)

In [ ]:
b.ndim

3

In [ ]:
b.size

12

In [ ]:
b.nbytes

96

In [ ]:
b.itemsize

8