**Numpy library**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more

In [ ]:
print('Welcome supriya kapse')

Welcome supriya kapse


In [ ]:
a = 2
a

2

In [ ]:
a = 2
b = 3
print('a = ' + str(a) + ' and ' + 'b = ' + str(b)) # convert int to str

a = 2 and b = 3


In [ ]:
type(a) # check type of variable a

int

In [ ]:
s1 = 'welcome supriya to RJ college'
type(s1)

str

In [ ]:
f=10.34546796547
type(f)

float

In [ ]:
a=[1,2,3]
a

[1, 2, 3]

In [ ]:
type(a)

list

In [ ]:
b=[4,5,6]
b

[4, 5, 6]

In [ ]:
c = []

for i in range(len(a)):
  c.append(a[i]*b[i])

print(c)

[4, 10, 18]


In [ ]:
c = []

for i in range(len(a)):
  c.append(a[i]+b[i])

print(c)

[5, 7, 9]


In [ ]:
import time
print('sleeping')

time.sleep(30)
print('done sleeping')

sleeping
done sleeping


**NumPy arange()**

 is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.

You can define the interval of the values contained in an array, space between them, and their type with four parameters of arange():

numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray
The first three parameters determine the range of the values, while the fourth specifies the type of the elements:

start is the number (integer or decimal) that defines the first value in the array.
stop is the number that defines the end of the array and isn’t included in the array.
step is the number that defines the spacing (difference) between each two consecutive values in the array and defaults to 1.
dtype is the type of the elements of the output array and defaults to None.

np.reshape(x, y) 

converts linear data to metric format (x(rows), y(columns))

In [ ]:
import numpy as np

a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


**.ndim()**

 function return the number of dimensions of an array.

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.name

**itemsize** 

returns the size (in bytes) of each element of a NumPy array

In [ ]:
a.itemsize

8

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
b=np.array([[11,13,14],[56,57,58]])
b

array([[11, 13, 14],
       [56, 57, 58]])

In [31]:
b.reshape(3,2)
b

array([[11, 13, 14],
       [56, 57, 58]])

In [32]:
d=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [33]:
e=d.reshape(2,5)
e

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')