In [1]:
import numpy
numpy.__version__

'1.19.5'

In [2]:
list1=[]
list1

[]

In [3]:
type(list1)

list

In [4]:
list2 = list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list3 = [str(c) for c in list2]
list3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
list4 = [1,10.2,'c','Amit',True]
list4

[1, 10.2, 'c', 'Amit', True]

In [7]:
type(list4)

list

In [8]:
[type(item) for item in list4]

[int, float, str, str, bool]

In [9]:
import array as ar
L = list(range(10))
A = ar.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [11]:
np.array([10.1,2,3,4])

array([10.1,  2. ,  3. ,  4. ])

In [12]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros((2,5),dtype='float32')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [15]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full((3,5), 3.0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [17]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [18]:
np.arange(0,2,0.5)

array([0. , 0.5, 1. , 1.5])

In [19]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.random.random((3,3))

array([[0.29151185, 0.1143252 , 0.63251763],
       [0.35831567, 0.68272155, 0.08948856],
       [0.86450438, 0.44116592, 0.61290848]])

In [21]:
np.random.normal(0,1,(3,3))

array([[ 1.87672353,  0.15595321,  0.09027074],
       [-2.20430398,  1.40422765,  1.21326228],
       [-1.17531384, -0.8558837 , -1.17548014]])

In [22]:
np.random.randint(0,10,(3,3))

array([[6, 1, 0],
       [3, 3, 7],
       [1, 3, 3]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.empty(3)

array([1., 1., 1.])

In [25]:
import numpy as np
np.random.seed(40)

x1 = np.random.randint(50, size=6)
x1

array([ 6, 27,  7, 37,  1, 12])

In [26]:
np.random.seed(100)
x2 = np.random.randint(200,size=(5,6,7))
x2

array([[[  8,  24,  67, 103,  87,  79, 176],
        [138,  94, 180,  98,  53,  66,  14],
        [ 34,  24, 143, 107,  60,  58, 144],
        [137,  93,  86, 130, 155, 108, 132],
        [159, 129, 141, 100,   4,  91, 187],
        [ 67, 135,  49, 175, 193,  61,  14]],

       [[183, 199,  80,   2, 121, 105, 147],
        [ 63, 181,  27,  56, 113, 158, 176],
        [ 47, 167, 109,  38, 172,  18, 192],
        [184, 162, 181,  17,  72,  13, 106],
        [ 30,  17,  53,  68, 178,  91, 181],
        [ 78,   0,  13, 185, 106, 131,  70]],

       [[131, 138, 188, 131, 105, 176, 180],
        [ 43,  36,   5,  71,  38,  94, 170],
        [ 84,  95, 114, 119,  76,  33,  58],
        [102, 170, 150,   0, 183, 147,  53],
        [196, 190,  50, 196, 163, 151,   9],
        [176,  21, 153, 182,   6, 165, 102]],

       [[122, 116, 186,  39, 107,  51,  30],
        [121,  66, 152, 183,  17,  45,  89],
        [173,  35,  16,  12,  86, 109,  67],
        [ 20, 138,   8, 158, 140, 146,  93],
    

In [27]:
np.random.seed(100)
x3 = np.random.randint(200, size=(4,2,2,3))
x3


array([[[[  8,  24,  67],
         [103,  87,  79]],

        [[176, 138,  94],
         [180,  98,  53]]],


       [[[ 66,  14,  34],
         [ 24, 143, 107]],

        [[ 60,  58, 144],
         [137,  93,  86]]],


       [[[130, 155, 108],
         [132, 159, 129]],

        [[141, 100,   4],
         [ 91, 187,  67]]],


       [[[135,  49, 175],
         [193,  61,  14]],

        [[183, 199,  80],
         [  2, 121, 105]]]])

In [28]:
np.random.seed(100)
x4 = np.random.randint(200, size=(2,4,2,2,3))
x4

array([[[[[  8,  24,  67],
          [103,  87,  79]],

         [[176, 138,  94],
          [180,  98,  53]]],


        [[[ 66,  14,  34],
          [ 24, 143, 107]],

         [[ 60,  58, 144],
          [137,  93,  86]]],


        [[[130, 155, 108],
          [132, 159, 129]],

         [[141, 100,   4],
          [ 91, 187,  67]]],


        [[[135,  49, 175],
          [193,  61,  14]],

         [[183, 199,  80],
          [  2, 121, 105]]]],



       [[[[147,  63, 181],
          [ 27,  56, 113]],

         [[158, 176,  47],
          [167, 109,  38]]],


        [[[172,  18, 192],
          [184, 162, 181]],

         [[ 17,  72,  13],
          [106,  30,  17]]],


        [[[ 53,  68, 178],
          [ 91, 181,  78]],

         [[  0,  13, 185],
          [106, 131,  70]]],


        [[[131, 138, 188],
          [131, 105, 176]],

         [[180,  43,  36],
          [  5,  71,  38]]]]])

In [29]:
x2.shape

(5, 6, 7)

In [30]:
x2.ndim

3

In [31]:
x2.size

210

In [32]:
x2.nbytes

1680

In [33]:
x2.itemsize

8